apiVersion: v1
kind: Service
metadata:
  name: randonet
  namespace: randonet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    vm.kubevirt.io/name: randonet-server
  sessionAffinity: None
  type: ClusterIP
